### PR TITLE
Breaking

### PR DESCRIPTION
**Pull request by notlee**
See https://github.com/Financial-Times/o-video/issues/141

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-video bundle size difference from 5.1.6 to df5d084998993a6c04ae0a6f922e2789ab7d4746
js: 0.33kb increase (0.17kb/gzip)
An insignificant difference was also found for: css

**Comment by origamiserviceuser** [comment]
o-video bundle size difference from 5.1.6 to f347b97da48c86ff111f488ad63dcf075004ebfe
js: 0.21kb increase (0.03kb/gzip)
css: 0.36kb increase (0.07kb/gzip)

**Comment by origamiserviceuser** [comment]
o-video bundle size difference from 5.1.6 to b049e1e9664756c37c60060e1543ab354861f553
js: 0.3kb increase (0.05kb/gzip)
css: 0.36kb increase (0.07kb/gzip)

**Comment by notlee** [comment]
This has been approved via other PRs, e.g. see https://github.com/Financial-Times/o-video/pull/148  https://github.com/Financial-Times/o-video/pull/146 https://github.com/Financial-Times/o-video/pull/143

**Comment by origamiserviceuser** [comment]
o-video bundle size difference from 5.1.6 to a1cca3416b73990e3331805479c8190b18c101a3
js: 0.25kb increase (0.03kb/gzip)
css: 0.3kb increase (0.05kb/gzip)

**Pull request merged**
