### PR TITLE
Stop error from google ads sdk spamming sentry

### PR DESCRIPTION
**Pull request by alexflorisca**

### CODE REVIEW

**Comment by alexflorisca** [comment]
Linting is failing because one of the class methods `loadAdsLibrary()` is now not using `this` anywhere. That's some strict linting right there

**Comment by JakeChampion** [comment]
@alexflorisca If you change the function from a method on the prototype to a static method on the class then it will pass linting.

**Review by remybach — DISMISSED** [review]
Looks good to me 👍

**Comment by alexflorisca** [comment]
@JakeChampion classy, done.

**Review by JakeChampion — DISMISSED** [review]

**Comment by alexflorisca** [comment]
@JakeChampion Can i get another tick please, forgot some of the things.

**Review by JakeChampion — APPROVED** [review]

**Pull request merged**
