### PR TITLE
If adverts haven't loaded when ad play should start following a placeholder click, play the video instead of doing nothing

### PR DESCRIPTION
**Pull request by rowanbeentje**

### CODE REVIEW

**Comment by AlbertoElias** [comment]
But currently it´s supposed to just wait for the ad to load so the ad always loads. It used to be the previous behaviour to just play the video, but some people didn't like it much =/

**Comment by rowanbeentje** [comment]
I thought this code was only used for when the ads are loaded, but you're right - it's called twice, once after video load, and once after advert manager load, and should kick off playing once both of those are true.

The problem is if no advert is loaded, due to something in the ads system - then the `adErrorHandler()` is invoked instead of the `adsManagerLoadedHandler()`, so this code path will never be reached.

So this pull request doesn't work right now but does need something similar done to make this work - I'll add some comments to `startAds` to show it needs to be called twice to work, and that's why the logic is there, and add a video play to the `adErrorHandler()` instead.  That sound correct @VladDubrovskis ?

**Comment by AlbertoElias** [comment]
Sounds good, I'll leave it to Jake to handle

**Comment by rowanbeentje** [comment]
Think that covers it...?

**Comment by JakeChampion** [comment]
Looks good 👍

**Pull request merged**
