### PR TITLE
add eslint config to repo to integrate with text editors

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-video bundle size difference from 6.0.3 to f12c31ec3b06918d5935016458c7bfe19532a000
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-video bundle size difference from 6.0.3 to 6288d8c30e5f613fa051d0ec9bc441a0f287faf2
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-video bundle size difference from 6.0.3 to edc42598cd9e7953dc1743505732e9a5743efc97
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-video bundle size difference from 6.0.3 to 72220a51e2d10f00ddaf801c6afd380787fa1297
No significant bundle size differences found.

**Review by notlee — DISMISSED** [review]

**Comment by origamiserviceuser** [comment]
o-video bundle size difference from 6.0.3 to 7721135db0ba6e1125483e6ba19bc3462d40adc5
No significant bundle size differences found.

**Review by notlee — APPROVED** [review]

**Pull request merged**
