### PR TITLE
Track `waiting` event

### LINKED ISSUE #124: We should track buffering events
https://github.com/Financial-Times/o-video/blob/166e5a23df77e08653e286308f8821aad0dbc10d/src/js/video.js#L241

https://developer.mozilla.org/en-US/docs/Web/Events/waiting

Relates to https://trello.com/c/PhYVid5N/276-loading-videos-on-ftcom.

We've _only just_ enabled streaming miss on the next media API's Fastly service, which should have dramatic improvements to the video load times.

### PR DESCRIPTION
**Pull request by chee**
closes #124

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-video bundle size difference from 6.0.11 to 2d81e15edf9f594d0826dfc4029959a555833740
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-video bundle size difference from 6.0.11 to 3136a803afe8b1508480ccb307853a16c8d1068e
No significant bundle size differences found.

**Review by JakeChampion — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
:tada: This PR is included in version v6.1.0 :tada:

**Comment by chee** [comment]
good work with the label adding, @JakeChampion! i forgot

**Pull request merged**
