### PR TITLE
Added showGuidance option for subtitles guidance

### PR DESCRIPTION
**Pull request by carlesandres**
We want to make the subtitles guidance optional, i.e. allow not to show a "subtitles not available" message even if the subtitles aren't available.

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-video bundle size difference from 5.1.6 to 4bd5fb879669d5cb07ed72778f5538ff677e0519
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-video bundle size difference from 5.1.6 to 3c3e6b55826a14e023e712a15727daf7e09ed4cf
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-video bundle size difference from 5.1.6 to 82694dd6ac9918cfb89e8e1d096b59b3ca59b619
No significant bundle size differences found.

**Review by chee — APPROVED** [review]
seems solid

**Review by binaryberry — APPROVED** [review]
Looks good to me!

**Review by umbobabo — APPROVED** [review]
LGTM 👍

**Pull request merged**
