### PR TITLE
Experimental closed-captions

### PR DESCRIPTION
**Pull request by commuterjoy**
Only supports English WebVTT at the moment. Because.

### CODE REVIEW

**Comment by JakeChampion** [comment]
Is this to be released as an experimental version of o-video?

**Comment by commuterjoy** [comment]
@JakeChampion nah, straight in to the mainline

**Comment by JakeChampion** [comment]
@commuterjoy sounds good, could we have some tests for this functionality?

**Comment by commuterjoy** [comment]
@JakeChampion aw, it's Friday. _Nobody_ writes tests on Fridays do they?

(will write tests)

**Comment by commuterjoy** [comment]
@JakeChampion ok - added a simple test.

**Review by ironsidevsquincy — APPROVED** [review]

**Pull request merged**
